---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: app
 labels:
  app: app
spec:
 replicas: 1
 selector:
  matchLabels:
   app: app
 template:
  metadata: 
   labels:
    app: app
  spec:
   containers:
   - name: app
     image: fazilniveus/counter:tagversion
     ports:
     - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 50
      targetPort: 5000
