---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
      labels:
        app: app
    spec:
      containers:
      - image: fazilniveus/counter:tagversion
        name: app
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"5002":{}}}'
  labels:
    app: app
spec:
  selector:
    app: app
  type: NodePort
  ports:
  - port: 5002
    protocol: TCP
